server:
  host:

spring:
  config:
    activate:
      on-profile: release

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false

management:
  endpoints:
    web:
      base-path: "/"
      exposure:
        include:
          - "health"
          - "info"
  endpoint:
    health:
      show-details: never
  info:
    env:
      enabled: false
    java:
      enabled: false

logging:
  file:
    path: ${KOPRINGBOOT_APP_LOG_PATH:logs/}
  level:
    ROOT: INFO
