server:
  port: ${KOPRINGBOOT_APP_PORT:8080}
  error:
    whitelabel:
      enabled: false

info:
  name: ${projectName}
  description: ${projectDescription}
  version: ${appVersion}${mayPrerelease}${buildMetadata}
  builtAt: ${builtAt}

spring:
  application:
    name: kopringboot-app
  profiles:
    # local, alpha, beta, release, test
    active: ${springAppProfile}
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        query:
          fail_on_pagination_over_collection_fetch: true
  sql:
    init:
      mode: ALWAYS
      schema-locations: classpath:/sql/schema/*.sql
      # data-locations:
  datasource:
    # Automatic database initialisation. Maybe conflict to hibernate.
    # https://docs.spring.io/spring-boot/docs/current/reference/html/howto-database-initialization.html
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:kopringboot-app;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
