spring:
  config:
    activate:
      on-profile: beta

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  file:
    path: ${KOPRINGBOOT_APP_LOG_PATH:logs/}
  level:
    ROOT: INFO
    com.github.francescojo: TRACE
    org.springframework.web.servlet: DEBUG
    org.springframework.web.filter: DEBUG
