spring:
  config:
    activate:
      on-profile: beta

logging:
  file:
    path: ${KOPRINGBOOT_APP_LOG_PATH:logs/}
  level:
    ROOT: INFO
    com.github.francescojo: TRACE
    org.springframework.web.servlet: DEBUG
    org.springframework.web.filter: DEBUG
