server:
  host:

spring:
  config:
    activate:
      on-profile: alpha

logging:
  file:
    path: ${KOPRINGBOOT_APP_LOG_PATH:logs/}
  level:
    ROOT: INFO
    com.github.francescojo: TRACE
    org.springframework.context: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.web.filter: TRACE
    org.springframework.web.servlet: TRACE
