spring:
  config:
    activate:
      on-profile: local

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    ROOT: INFO
    com.github.francescojo: TRACE
    org.springframework.context: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.web.filter: TRACE
    org.springframework.web.servlet: TRACE
